name: udd-telefonica-challenge
channels:
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - pandas
  - geopandas
  - numpy
  - seaborn
  - pip
  - pip:
    - python-dotenv==0.21.0
    - jupyterlab==3.4.8
